(defun add (x y)
  (+ x y)
)

(add 3 4)


; _add:
;   generated by evalTerminal()
;   pop bx <- y
;   pop ax <- x
;   add ax, bx
;   push ax
;   end of generation
;   pop ax
;   ret
; when called:
; (add 5 6) ->
; push 5
; push 6
; call _add
; push ax
